language: python
cache: pip


services:
  - redis-server
  - postgresql
  - mongodb

before_script:
  - psql -c "CREATE DATABASE aiopg;" -U postgres
  - psql -c "CREATE USER aiopg WITH PASSWORD 'example';" -U postgres


install:
  - pip install tox

jobs:
  include:
    - stage: syntax
      script: tox
      python: 3.6
      env: TOXENV=syntax


    - stage: test
      script: tox
      env: TOXENV=py36,codecov
      python: 3.6

    - stage: test
      script: tox
      env: TOXENV=py37,codecov
      python: 3.7